### ISSUE TITLE
linux crash

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/desktop#30]
Gitter linux client just crashed. It had been running for a couple of days. Last error was:
```
[8280:0217/091947:INFO:CONSOLE(292)] ""mainWindow:focus ===================="", source: app://gitter/index.js (292)
[8280:0217/092020:INFO:CONSOLE(106)] ""rtc: Message on channel /api/v1/user/549759ffdb8155e6700e1c5e out of sequence. Expected 10 got 4"", source: /tmp/.org.chromium.Chromium.ZGslum/node_modules/gitter-realtime-client/lib/realtime-client.js (106)
[8280:0217/092021:INFO:CONSOLE(30)] ""Caught exception: TypeError: Cannot read property 'sendMessage' of undefined"", source: app://gitter/index.js (30)
[8280:0217/092021:INFO:CONSOLE(31)] ""TypeError: Cannot read property 'sendMessage' of undefined
 at Object.Faye_Class._sendEnvelope (/tmp/.org.chromium.Chromium.ZGslum/node_modules/gitter-realtime-client/node_modules/gitter-faye/javascript/protocol/dispatcher.js:125:39)
 at /tmp/.org.chromium.Chromium.ZGslum/node_modules/gitter-realtime-client/node_modules/gitter-faye/javascript/protocol/dispatcher.js:169:14"", source: app://gitter/index.js (31)
```

v2.2.4

via @gmorph

**Comment by suprememoocow** [comment]
This is probably fixed by https://github.com/gitterHQ/desktop/commit/82eca2bfef7466d38f2766e08a8c495c6b6e7583.

**Comment by MadLittleMods** [comment]
Closing for the lack of response suggesting it was fixed from the change @suprememoocow mentioned.
