### ISSUE TITLE
Mac crash

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/desktop#35]
```
[89313:0224/173753:INFO:CONSOLE(31)] ""TypeError: Cannot set property 'windowState' of null\n    at saveWindowState (app://gitter/node_modules/node-webkit-winstate/index.js:106:33)\n    at Window.\u003Canonymous\u003E (app://gitter/node_modules/node-webkit-winstate/index.js:161:5)\n    at Window.EventEmitter.emit (events.js:101:17)\n    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:795:26)"", source: app://gitter/index.js (31)
```

**Comment by trevorah** [comment]
split('\n'):
```
TypeError: Cannot set property 'windowState' of null
    at saveWindowState (app://gitter/node_modules/node-webkit-winstate/index.js:106:33)
    at Window.\u003Canonymous\u003E (app://gitter/node_modules/node-webkit-winstate/index.js:161:5)
    at Window.EventEmitter.emit (events.js:101:17)
    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:795:26)
source: app://gitter/index.js (31)
```
