### ISSUE TITLE
App doesn't start when behind a proxy

### ISSUE THREAD

**Issue by nwinkler** [gitterHQ/desktop#49]
When starting the desktop app from behind a proxy, I enter my GitHub credentials, then the app screen turns white, and then the app crashes:

```
> gitter-desktop@0.0.1 start /Users/nils.winkler/workspaces/Gitter/desktop
> nodewebkit nwapp

[54488:0325/154529:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[54489:0325/154529:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[54487:0325/154530:INFO:CONSOLE(40)] ""Gitter2.3.1"", source: app://gitter/index.js (40)
[54487:0325/154530:INFO:CONSOLE(66)] ""Rebuilding tray menu"", source: /Users/nils.winkler/workspaces/Gitter/desktop/nwapp/components/tray-menu.js (66)
[54487:0325/154530:INFO:CONSOLE(16)] ""Checking for updates"", source: /Users/nils.winkler/workspaces/Gitter/desktop/nwapp/utils/auto-update.js (16)
[54487:0325/154530:INFO:CONSOLE(364)] ""got 0 cookies"", source: app://gitter/index.js (364)
[54487:0325/154530:INFO:CONSOLE(368)] ""deleted all cookies"", source: app://gitter/index.js (368)
[54487:0325/154642:INFO:CONSOLE(85)] ""createCredentials() is deprecated, use tls.createSecureContext instead"", source: util.js (85)
[54487:0325/154646:INFO:CONSOLE(18)] ""newVersionExists? undefined"", source: /Users/nils.winkler/workspaces/Gitter/desktop/nwapp/utils/auto-update.js (18)
[54487:0325/154757:INFO:CONSOLE(28)] ""Caught exception: TypeError: object is not a function"", source: app://gitter/index.js (28)
[54487:0325/154757:INFO:CONSOLE(29)] ""TypeError: object is not a function\n    at /Users/nils.winkler/workspaces/Gitter/desktop/nwapp/lib/login-view.js:56:9\n    at /Users/nils.winkler/workspaces/Gitter/desktop/nwapp/node_modules/oauth/lib/oauth2.js:177:18\n    at ClientRequest.\u003Canonymous\u003E (/Users/nils.winkler/workspaces/Gitter/desktop/nwapp/node_modules/oauth/lib/oauth2.js:148:5)\n    at ClientRequest.EventEmitter.emit (events.js:104:17)\n    at TLSSocket.socketErrorListener (_http_client.js:267:9)\n    at TLSSocket.EventEmitter.emit (events.js:126:20)\n    at net.js:442:14\n    at process._tickCallback (node.js:382:11)"", source: app://gitter/index.js (29)
```

**Comment by bjackson** [comment]
Same issue, after login, screen turns white, to black, then crashes.

**Comment by hellboy81** [comment]
Have the same issue

**Comment by dimahali** [comment]
+1

**Comment by necrose99** [comment]
+1

**Comment by rohancragg** [comment]
I have a similar issue. I downloaded the desktop app whilst behind a corporate proxy (bloxx) which intercepts all traffic and I cannot get raound it, cannot modify DNS etc.

The issue only causes a problem with the 'Allow / Deny' screen that tries to ask if it's OK to log in to GitHub for me. 

Whilst outside of the corp netwrok I used my home ISP to get past hat screen and I no longer have issues. So whatever is happening during the Allow/Deny auth step doesn't work well with the proxy.

**Comment by MadLittleMods** [comment]
@rohancragg You can authorize manually with these steps, https://gist.github.com/MadLittleMods/01158db1056da3b86495

**Comment by rohancragg** [comment]
@MadLittleMods  - thanks. As I said, I managed to get past the issue by using my home ISP. I'm just trying to add some detail to the issue to help someone repro the issue and hopefully fix Gitter Desktop so that it will work from behind a proxy?

**Comment by rodrigortz** [comment]
This is my exact same problem...
